[build]
  command = "npx prisma@5.22.0 generate && NEXT_PUBLIC_SKIP_DB=true npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"
  NPM_CONFIG_PRODUCTION = "false"

[functions]
  node_bundler = "nft"
