export const SITE_NAME = "WinTech AI";
export const API_BASE = "/api";

export const EMAIL = "wintech.ia@gmail.com";
export const WHATSAPP_NUMBER = "+573025847979";
export const WHATSAPP_URL = `https://wa.me/573025847979?text=${encodeURIComponent("Hola, me interesa conocer más sobre WinTech AI")}`;

export const SERVICES = [
  {
    id: "chatbot-ia",
    title: "Chatbot IA",
    shortDesc: "Atención automática 24/7 para WhatsApp y tu web. Califica leads y agenda citas.",
    description: "Atención automática 24/7 para WhatsApp y tu web. Califica leads y agenda citas sin intervención humana.",
    icon: "MessageSquareText",
    image: "/images/services/chatbot.svg",
    benefits: [
      "Atención 24/7 sin interrupciones",
      "Calificación automática de leads",
      "Agendamiento de citas integrado",
      "Reduce hasta 70% de consultas repetitivas",
      "Transferencia inteligente a humano",
    ],
    roi: "Nuestros clientes ven un incremento del 35-50% en citas agendadas y reducen costos de recepción en un 60%.",
    precio: "Desde $497.000/mes",
  },
  {
    id: "recepcionista-voz",
    title: "Recepcionista de Voz IA",
    shortDesc: "Wincho AI atiende llamadas, agenda citas y responde preguntas con voz natural.",
    description: "Wincho AI atiende llamadas, agenda citas y responde preguntas frecuentes con voz natural.",
    icon: "Phone",
    image: "/images/services/voz-ia.svg",
    benefits: [
      "Atención telefónica 24/7",
      "Voz natural en español colombiano",
      "Agendamiento automático de citas",
      "Integración con Google Calendar",
      "Nunca pierde una llamada",
    ],
    roi: "Recupera el 80% de llamadas perdidas que antes se iban a la competencia. ROI positivo en semana 1.",
    precio: "Desde $797.000/mes",
  },
  {
    id: "automatizacion",
    title: "Automatización de Marketing",
    shortDesc: "Secuencias de seguimiento por email y WhatsApp que convierten leads en clientes.",
    description: "Secuencias de seguimiento por email y WhatsApp que convierten leads en clientes.",
    icon: "Zap",
    image: "/images/services/automatizacion.svg",
    benefits: [
      "Secuencias de email personalizadas",
      "Campañas de WhatsApp masivas",
      "Recordatorios automáticos de citas",
      "Reportes de conversión en tiempo real",
      "Integración con CRM",
    ],
    roi: "Aumenta la conversión de leads en clientes hasta un 45% con seguimiento automático.",
    precio: "Desde $397.000/mes",
  },
  {
    id: "seo-local",
    title: "SEO Local + Google Business",
    shortDesc: "Posiciona tu negocio en Google Maps y búsquedas locales para atraer clientes.",
    description: "Posiciona tu negocio en Google Maps y búsquedas locales para atraer clientes cercanos.",
    icon: "MapPin",
    image: "/images/services/seo-local.svg",
    benefits: [
      "Optimización de Google Business Profile",
      "Gestión y respuesta de reseñas",
      "Contenido optimizado para búsquedas locales",
      "Reportes mensuales de posicionamiento",
      "Estrategia de backlinks locales",
    ],
    roi: "Aparece en el 87% de las búsquedas locales de tus clientes potenciales. Aumenta visitas web un 200%.",
    precio: "Desde $297.000/mes",
  },
  {
    id: "wincho-ai",
    title: "Wincho AI - Asistente de Voz",
    shortDesc: "Asistente de voz con IA que atiende llamadas, agenda citas y responde 24/7 con voz natural.",
    description: "Wincho AI es nuestro producto estrella. Un asistente de voz con inteligencia artificial que atiende llamadas telefónicas, agenda citas, responde preguntas frecuentes y captura leads con voz natural en español colombiano.",
    icon: "Phone",
    image: "/images/services/voz-ia.svg",
    benefits: [
      "Atención telefónica 24/7 con voz natural",
      "Agendamiento automático de citas",
      "Captura de leads por teléfono",
      "Integración con CRM y calendario",
      "Voz natural en español colombiano",
    ],
    roi: "Recupera el 80% de llamadas perdidas. Cada llamada atendida es un cliente potencial capturado.",
    precio: "Desde $797.000/mes",
  },
];

export const NICHOS = [
  {
    id: "clinica-estetica",
    title: "Clínicas Estéticas",
    description: "Agenda citas automáticas, envía recordatorios pre/post procedimiento y captura leads de Instagram.",
    icon: "Sparkles",
    color: "from-pink-500 to-rose-500",
    image: "/images/nichos/clinica-estetica.svg",
    chatPrompt: "clinica-estetica",
  },
  {
    id: "dentistas",
    title: "Consultorios Dentales",
    description: "Reduce inasistencias con recordatorios inteligentes y atiende consultas fuera de horario.",
    icon: "Smile",
    color: "from-blue-500 to-cyan-500",
    image: "/images/nichos/dentista.svg",
    chatPrompt: "dentistas",
  },
  {
    id: "abogados",
    title: "Bufetes de Abogados",
    description: "Captura consultas urgentes 24/7, clasifica casos potenciales y agenda consultas iniciales.",
    icon: "Scale",
    color: "from-amber-500 to-orange-500",
    image: "/images/nichos/abogados.svg",
    chatPrompt: "abogados",
  },
  {
    id: "talleres",
    title: "Talleres Mecánicos",
    description: "Agenda servicios, envía recordatorios de mantenimiento y responde consultas sobre precios.",
    icon: "Wrench",
    color: "from-green-500 to-emerald-500",
    image: "/images/nichos/taller.svg",
    chatPrompt: "talleres",
  },
  {
    id: "inmobiliarios",
    title: "Inmobiliarias",
    description: "Atiende consultas de propiedades fuera de horario, agenda visitas y captura datos de compradores.",
    icon: "Building",
    color: "from-purple-500 to-violet-500",
    image: "/images/nichos/inmobiliaria.svg",
    chatPrompt: "inmobiliarios",
  },
];

export const PLANS = [
  {
    id: "starter",
    name: "Starter",
    tagline: "Para negocios que empiezan con IA",
    price: "$497.000",
    period: "/mes",
    popular: false,
    features: [
      "Chatbot WhatsApp básico",
      "1 nicho configurado",
      "500 conversaciones/mes",
      "Soporte por email",
      "Reportes básicos",
      "Dashboard de métricas",
    ],
    cta: "Empezar Ahora",
  },
  {
    id: "growth",
    name: "Growth",
    tagline: "Para negocios en crecimiento",
    price: "$997.000",
    period: "/mes",
    popular: true,
    features: [
      "Chatbot WhatsApp avanzado",
      "Recepcionista de voz (Wincho AI)",
      "3 nichos configurados",
      "Conversaciones ilimitadas",
      "Automatización de marketing",
      "Soporte prioritario",
      "Reportes avanzados",
      "Dashboard en tiempo real",
    ],
    cta: "Más Popular",
  },
  {
    id: "enterprise",
    name: "Enterprise",
    tagline: "Para operaciones a escala",
    price: "Personalizado",
    period: "",
    popular: false,
    features: [
      "Todo de Growth",
      "Nichos ilimitados",
      "API personalizada",
      "Integraciones custom",
      "Account manager dedicado",
      "SLA garantizado",
      "Onboarding presencial",
      "Soporte 24/7 prioritario",
    ],
    cta: "Contáctanos",
  },
];

export const TESTIMONIALS = [
  {
    name: "Dra. María Fernanda",
    role: "Clínica Estética Vitalidad",
    text: "Desde que implementamos el chatbot, agendamos 40% más citas. Los pacientes pueden reservar a cualquier hora sin esperar.",
    rating: 5,
  },
  {
    name: "Carlos Andrés Gómez",
    role: "Bufete Legal & Asociados",
    text: "Wincho AI atiende nuestras llamadas fuera de horario. Hemos capturado consultas que antes se perdían los fines de semana.",
    rating: 5,
  },
  {
    name: "Ana Lucía Restrepo",
    role: "Centro Odontológico Sonrisas",
    text: "Los recordatorios automáticos redujeron nuestras inasistencias en un 60%. El ROI se pagó en el primer mes.",
    rating: 5,
  },
];
