export const WHATSAPP_URL = 'https://wa.me/573025847979?text=Hola%20WinTech%20AI%2C%20me%20interesa%20conocer%20m%C3%A1s%20sobre%20sus%20servicios%20de%20IA';
export const WHATSAPP_NUMBER = '+57 302 584 7979';
export const EMAIL = 'wintech.ia@gmail.com';
export const MAP_COORDS = { lat: 3.539375, lng: -76.310625 };
export const GOOGLE_MAPS_EMBED = 'https://www.google.com/maps/embed?pb=!1m14!1m12!1m3!1d3000!2d-76.310625!3d3.539375!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!5e0!3m2!1ses!2sco!4v1700000000000!5m2!1ses!2sco';

export const SERVICES = [
  {
    id: 'smart-web-chat',
    title: 'Smart Web Chat IA',
    shortDesc: 'Chatbot que califica leads y agenda citas 24/7',
    description: 'Un chatbot conversacional entrenado con la información de tu negocio. Califica leads, responde preguntas y agenda citas automáticamente sin que tú levantes un dedo.',
    icon: 'MessageSquareText',
    image: 'https://cdn.abacus.ai/images/02ea5195-44e3-45c5-aaa8-7484d445f52e.png',
    benefits: ['Atención 24/7 sin contratar personal', 'Calificación automática de leads', 'Agenda citas directamente', 'Respuestas personalizadas para tu negocio', 'Integración con WhatsApp'],
    roi: 'Recupera hasta el 40% de leads que antes se perdían por no contestar a tiempo.',
    precio: 'Desde COP $280.000/mes',
  },
  {
    id: 'recepcionista-voz',
    title: 'Recepcionista de Voz IA',
    shortDesc: 'Contesta llamadas perdidas con voz casi humana',
    description: 'Una recepcionista virtual que contesta llamadas con voz natural, responde preguntas frecuentes y agenda citas. Recupera el 62% de llamadas que nunca son contestadas.',
    icon: 'Phone',
    image: 'https://cdn.abacus.ai/images/89e1978f-2ede-4f18-b782-eff30c055002.png',
    benefits: ['Contesta el 100% de las llamadas', 'Voz natural casi humana', 'Agenda citas automáticamente', 'Disponible 24/7 sin descanso', 'Recupera llamadas perdidas'],
    roi: 'El 62% de las llamadas a negocios locales nunca son contestadas. Cada una es un cliente perdido.',
    precio: 'Incluido en Plan Crecimiento',
  },
  {
    id: 'reactivador-base-datos',
    title: 'Reactivador de Base de Datos',
    shortDesc: 'Recupera clientes antiguos automáticamente',
    description: 'Sistema que reactiva clientes pasados de tu negocio mediante automatizaciones inteligentes. Genera caja inmediata reactivando relaciones con clientes que ya te conocen.',
    icon: 'DatabaseZap',
    image: 'https://cdn.abacus.ai/images/5de0b8d9-569d-4926-9b48-593f7abc082b.png',
    benefits: ['Genera ingresos inmediatos', 'Reactiva clientes que ya te conocen', 'Automatización completa', 'Campañas multicanal: SMS, Email, WhatsApp', 'ROI inmediato desde el primer mes'],
    roi: 'Genera caja inmediata reactivando entre el 15-30% de tu base de clientes inactivos.',
    precio: 'Incluido en Plan Dominio Total',
  },
  {
    id: 'generador-resenas',
    title: 'Generador de Reseñas',
    shortDesc: 'Mejora tu reputación online automáticamente',
    description: 'Sistema automatizado que solicita reseñas a tus clientes después de cada servicio. Mejora tu ranking en Google y construye una reputación sólida sin esfuerzo manual.',
    icon: 'Star',
    image: 'https://cdn.abacus.ai/images/dbee02d2-5ccb-4ad9-858d-467a52112207.png',
    benefits: ['Automatiza solicitud de reseñas', 'Mejora ranking en Google Maps', 'Filtra reseñas negativas antes', 'Aumenta la confianza de nuevos clientes', 'Reportes de reputación mensual'],
    roi: 'Los negocios con más de 50 reseñas positivas reciben 3x más clientes que la competencia.',
    precio: 'Incluido en Plan Crecimiento',
  },
  {
    id: 'seo-local',
    title: 'SEO Local Programático',
    shortDesc: 'Domina las búsquedas locales en Google',
    description: 'Creamos páginas individuales optimizadas por servicio + ciudad para que domines las búsquedas locales. Cuando alguien busca lo que ofreces en tu zona, tú apareces primero.',
    icon: 'Search',
    image: 'https://cdn.abacus.ai/images/8bc75a2c-a0f4-46b6-b21e-62d2e66b55b1.png',
    benefits: ['Domina búsquedas locales', 'Páginas por servicio + ciudad', 'Tráfico orgánico constante', 'Posicionamiento duradero en Google', 'Clientes nuevos cada mes sin pagar publicidad'],
    roi: 'El 46% de las búsquedas en Google tienen intención local. Si no apareces, tu competencia sí.',
    precio: 'Incluido en Plan Dominio Total',
  },
];

export const NICHOS = [
  {
    id: 'clinica-estetica',
    title: 'Clínicas Estéticas',
    icon: 'Sparkles',
    description: 'Agenda más pacientes y responde consultas de tratamientos las 24 horas, sin perder ni una oportunidad.',
    image: 'https://cdn.abacus.ai/images/4204d72d-2db5-4ec9-b39a-b99191d10a5b.png',
    chatPrompt: 'Eres el asistente virtual de "Clínica Belleza Total", una clínica de medicina estética en Palmira, Valle del Cauca. Ofreces tratamientos faciales, corporales, bótox, ácido hialurónico, depilación láser y más. El horario es de lunes a sábado de 8am a 6pm. La consulta de valoración cuesta COP $80.000. Tu tono es profesional, cálido y empático. Usas expresiones colombianas naturales.',
  },
  {
    id: 'dentistas',
    title: 'Dentistas',
    icon: 'Smile',
    description: 'Llena tu agenda de pacientes nuevos y consigue más reseñas positivas en Google automáticamente.',
    image: 'https://cdn.abacus.ai/images/a4d89442-05f8-4b61-9594-20b2a391b08f.png',
    chatPrompt: 'Eres el asistente virtual de "Sonrisa Perfecta", una clínica odontológica en Palmira, Valle del Cauca. Ofreces odontología general, ortodoncia, implantes dentales, blanqueamiento y estética dental. Horario: lunes a sábado 7am-7pm. Valoración inicial COP $50.000. Tu tono es profesional y cercano con expresiones colombianas naturales.',
  },
  {
    id: 'abogados',
    title: 'Abogados',
    icon: 'Scale',
    description: 'Captura y califica casos potenciales automáticamente, para que te enfoques en lo que mejor haces: ganar casos.',
    image: 'https://cdn.abacus.ai/images/247692a5-b2a3-44b4-b650-3fb43a071d54.png',
    chatPrompt: 'Eres el asistente virtual de "Bufete Justicia Legal", una firma de abogados en Palmira, Valle del Cauca. Se especializan en derecho laboral, civil, comercial, penal y de familia. Consulta inicial COP $150.000. Horario: lunes a viernes 8am-6pm, sábados 8am-12pm. Tu tono es profesional, serio pero accesible, con expresiones colombianas naturales.',
  },
  {
    id: 'talleres',
    title: 'Talleres Mecánicos',
    icon: 'Wrench',
    description: 'No pierdas más clientes por no contestar. Tu taller disponible para agendar servicios a cualquier hora.',
    image: 'https://cdn.abacus.ai/images/c27e17cc-74aa-4b6b-9bc2-66ad385a7b2a.png',
    chatPrompt: 'Eres el asistente virtual de "AutoPro Taller", un taller mecánico especializado en Palmira, Valle del Cauca. Ofreces mecánica general, electricidad automotriz, frenos, suspensión, cambio de aceite y diagnóstico computarizado. Horario: lunes a sábado 7am-6pm. Revisión general desde COP $80.000. Tu tono es directo, amigable y práctico con expresiones colombianas naturales.',
  },
  {
    id: 'inmobiliarias',
    title: 'Inmobiliarias',
    icon: 'Home',
    description: 'Atiende consultas de compradores e inquilinos al instante y agenda visitas sin esfuerzo manual.',
    image: 'https://cdn.abacus.ai/images/60a59a7b-754b-4836-ada4-e3fb40c1598a.png',
    chatPrompt: 'Eres el asistente virtual de "Hogar Ideal Inmobiliaria", una agencia inmobiliaria en Palmira, Valle del Cauca. Ofrecen venta y arriendo de casas, apartamentos, locales y lotes en Palmira, Cali y el Valle del Cauca. Consulta gratuita. Horario: lunes a sábado 8am-6pm. Tu tono es profesional, entusiasta y servicial con expresiones colombianas naturales.',
  },
];

export const PLANS = [
  {
    name: 'Impulso',
    tagline: 'Tu negocio en línea, con inteligencia',
    color: 'green',
    setup: '1.800.000',
    setupUsd: '~$430 USD',
    monthly: '280.000',
    monthlyUsd: '~$67 USD',
    popular: false,
    features: [
      { name: 'Sitio Web Inteligente', included: true },
      { name: 'Chatbot IA Básico', included: true },
      { name: 'Formulario + Calendario', included: true },
      { name: 'WhatsApp Business', included: true },
      { name: 'Hosting + SSL + Mantenimiento', included: true },
      { name: 'Recepcionista de Voz IA', included: false },
      { name: 'CRM + Automatización', included: false },
      { name: 'Reseñas Google Auto', included: false },
      { name: 'SEO Local Programático', included: false },
    ],
    ideal: 'Peluquerías, tiendas, restaurantes, profesionales independientes',
  },
  {
    name: 'Crecimiento',
    tagline: 'Tu vendedor digital 24/7',
    color: 'blue',
    setup: '3.500.000',
    setupUsd: '~$835 USD',
    monthly: '580.000',
    monthlyUsd: '~$138 USD',
    popular: true,
    features: [
      { name: 'Todo del Plan Impulso', included: true },
      { name: 'Chatbot IA Avanzado', included: true },
      { name: 'Recepcionista de Voz IA', included: true },
      { name: 'CRM + Seguimiento Automático', included: true },
      { name: 'Reseñas Google Auto', included: true },
      { name: 'Pop-ups Inteligentes', included: true },
      { name: 'Reportes Mensuales', included: true },
      { name: 'SEO Local Programático', included: false },
      { name: 'Reactivador de BD', included: false },
    ],
    ideal: 'Clínicas, consultorios, talleres, bufetes, inmobiliarias',
  },
  {
    name: 'Dominio Total',
    tagline: 'La máquina de ventas que nunca duerme',
    color: 'purple',
    setup: '6.500.000',
    setupUsd: '~$1.550 USD',
    monthly: '1.150.000',
    monthlyUsd: '~$274 USD',
    popular: false,
    features: [
      { name: 'Todo del Plan Crecimiento', included: true },
      { name: 'Ecosistema Completo 4 Capas', included: true },
      { name: 'Agente IA Multicanal', included: true },
      { name: 'CRM Completo + Pipeline', included: true },
      { name: 'Reactivador de BD', included: true },
      { name: 'SEO Local Programático', included: true },
      { name: 'Funnels con Agentes IA', included: true },
      { name: 'Campañas Automatizadas', included: true },
      { name: 'Soporte VIP 24/7', included: true },
    ],
    ideal: 'Clínicas multi-sede, franquicias, empresas con equipo comercial',
  },
];

export const TESTIMONIALS = [
  {
    name: 'Dra. María Fernández',
    role: 'Directora, Clínica Estética Renacer',
    image: 'https://cdn.abacus.ai/images/3e9b35e9-b5ba-44f2-bfae-1e3d0a0d6d8d.png',
    content: 'Desde que implementamos el chatbot de WinTech, nuestras citas agendadas aumentaron un 45%. El sistema contesta las 24 horas y nuestros pacientes aman la rapidez.',
    rating: 5,
  },
  {
    name: 'Carlos Ramírez',
    role: 'Gerente, TallerPro Automotriz',
    image: 'https://cdn.abacus.ai/images/0d578eb1-f7af-4ecb-9e23-767f74309ede.png',
    content: 'Antes perdíamos el 60% de las llamadas. Ahora la recepcionista IA contesta todo y agenda las citas. Nuestros ingresos subieron un 30% en tres meses.',
    rating: 5,
  },
  {
    name: 'Dra. Ana Lucía Torres',
    role: 'Odontóloga, Sonrisa Brillante',
    image: 'https://cdn.abacus.ai/images/9d2c6cac-5f27-4098-bcf3-70b51403b275.png',
    content: 'Las reseñas automáticas de Google cambiaron todo. Pasamos de 12 a más de 80 reseñas en 4 meses. Ahora los pacientes llegan diciendo que nos encontraron por Google.',
    rating: 5,
  },
];
